apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo-svc"
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        env:
        - name: MONGO_INITDB_DATABASE
          value: "strapi"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: strapi
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: strapi
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-ps
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-ps
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
