apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
      - name: strapi
        image: strapi/strapi:latest
        env:
        - name: APP_NAME
          value: "strapi-app"
        - name: DATABASE_CLIENT
          value: "mongo"
        - name: DATABASE_HOST
          value: "mongo-svc"
        - name: DATABASE_PORT
          value: "27017"
        - name: DATABASE_NAME
          value: "strapi"
        - name: DATABASE_USERNAME
          value: ""
        - name: DATABASE_PASSWORD
          value: ""
        - name: DATABASE_SSL
          value: "false"
        ports:
        - containerPort: 1337